version: '3.8'

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - app2
      - db
    container_name: app
    ports:
      - '8092:8080'
    environment:
      - DATABASE_URL=jdbc:postgresql://db:5432
      - DATABASE_NAME=integration
      - DATABASE_USERNAME=user
      - DATABASE_PASSWORD=user
    restart: always

  app2:
    image: interaction2
    hostname: app2
    container_name: app2
    ports:
      - '8090:8082'
    restart: always

  db:
    image: postgres:14
    ports:
      - '5433:5432'
    container_name: integration_db
    environment:
      - POSTGRES_DB=integration
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=user
    volumes:
      - ./postgres-data:/var/lib/postgresql/integration-service

  redis:
    image: redis:7.0.12
    ports:
      - '6379:6379'




